name: Build YouTube App

on:
  push:
    branches: [ "main" ]   
  workflow_dispatch:      

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable
      run: pyinstaller --onefile --windowed --icon=icono.ico youtube.py

    - name: Upload Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/youtube.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
